# 识别到关闭按钮之后 偏移多少像素之后进行点击 会在当前值的基础上 [-10, 10]
close_offsetx: 400
close_offsety: 0
# 识别到完成按钮之后 偏移多少像素之后进行点击 会在当前值的基础上 [-10, 10]
success_offsetx: 0
success_offsety: 0
# 点击关闭按钮之后，多少秒后点击确认按钮 会在当前值的基础上 [-1, 1]
await_time: 3
# 当前进程进行完毕之后，多少秒进行下次进程
end_time: 2
